# containerized test environment

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    image: travioli-backend-test
    volumes:
      - ./backend:/usr/src/app
      - backend_test_node_modules:/usr/src/app/node_modules
    # DNS resolves request origin and database
    environment:
      - PORT=5000
      - NODE_ENV=test
      - DATABASE_URL=postgresql://user:password@db:5432/testdb
      - REDIS_URL=redis://redis:6379
    command: sh -c "tail -f /dev/null"
    depends_on:
      - db
      - redis
    container_name: travioli-backend-test
  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    container_name: travioli-redis-test
  db:
    # running local postgres db for testing
    image: postgis/postgis:17-3.5-alpine
    environment:
      # hardcoding only for test purposes
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - test_database:/var/lib/postgresql/data
    container_name: travioli-database-test

volumes:
  backend_test_node_modules:
  test_database:
