# containerized production environment
# just simulating the production environment

services:

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # poll every 60 sec
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: watchtower

  backend:
    image: ichirojwang/travioli-backend:latest
    env_file: ./backend/.env
    ports:
      - 5000:5000
    command: sh -c "npx prisma db push --skip-generate && npm run start"
    depends_on:
      - database
      - redis_cache
    container_name: travioli-backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      args:
        VITE_MAPS_API: ${VITE_MAPS_API}
    image: travioli-frontend:prod
    ports:
      - 80:80
    container_name: travioli-frontend
    depends_on:
      - backend

  # running local postgres db for simulating production
  database:
    image: postgis/postgis:17-3.5-alpine
    env_file: ./backend/.env
    volumes:
      - travioli_database:/var/lib/postgresql/data
    container_name: travioli-database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  
  # running local redis cache for simulating production
  redis_cache:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    volumes:
      - travioli_redis:/data
    container_name: travioli-redis
    labels:
      - "com.centurylinklabs.watchtower.enable=false"


volumes:
  travioli_database:
  travioli_redis: