services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    environment:
      - PORT=5000
      - REQUEST_ORIGINS=http://localhost:5000,http://frontend:5173
      - DATABASE_URL=postgresql://user:password@db:5432/devdb
    ports:
      - 5000:5000
    command: npm run dev
    depends_on:
      - db
    container_name: travioli-backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    environment:
      - VITE_PORT=5173
      - VITE_BACKEND_URL=http://backend:5000
    ports:
      - 5173:5173
    container_name: travioli-frontend
  db:
    image: postgres
    environment:
      # hardcoding only for dev purposes
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    volumes:
      - database:/var/lib/postgresql/data
    container_name: travioli-database

volumes:
  frontend_node_modules:
  backend_node_modules:
  database:
