# containerized dev environment

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: travioli-backend-dev
    volumes:
      - ./backend:/usr/src/app
      - backend_dev_node_modules:/usr/src/app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - REQUEST_ORIGIN=http://frontend:5173
      - DATABASE_URL=postgresql://user:password@db:5432/devdb
      - REDIS_URL=redis://redis:6379
    ports:
      - 5000:5000
    command: npm run dev
    depends_on:
      - db
      - redis
    container_name: travioli-backend-dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: travioli-frontend-dev
    volumes:
      - ./frontend:/usr/src/app
      - frontend_dev_node_modules:/usr/src/app/node_modules
    environment:
      - PORT=5173
      - VITE_BACKEND_URL=http://backend:5000
    ports:
      - 5173:5173
    command: npm run dev
    container_name: travioli-frontend-dev
  redis:
    image: redis:8.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    container_name: travioli-redis-dev
  db:
    # running local postgres db for development
    image: postgis/postgis:17-3.5-alpine
    environment:
      # hardcoding only for dev purposes
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devdb
    volumes:
      - dev_database:/var/lib/postgresql/data
    container_name: travioli-database-dev
  nginx:
    # for reverse proxying requests from frontend to backend. see /nginx/dev.conf
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - db
      - redis
    container_name: travioli-nginx-dev

volumes:
  frontend_dev_node_modules:
  backend_dev_node_modules:
  dev_database:
  redis_data:
