/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This is the backend API. This doc was generated on 2025-09-11.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthLoginPostRequest
 */
export interface AuthLoginPostRequest {
    /**
     * A valid email address
     * @type {string}
     * @memberof AuthLoginPostRequest
     */
    'email': string;
    /**
     * A password with minimum 8 characters
     * @type {string}
     * @memberof AuthLoginPostRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface AuthResendVerificationEmailPostRequest
 */
export interface AuthResendVerificationEmailPostRequest {
    /**
     * A valid email address
     * @type {string}
     * @memberof AuthResendVerificationEmailPostRequest
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface AuthSignupPostRequest
 */
export interface AuthSignupPostRequest {
    /**
     * A valid email address
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    'email': string;
    /**
     * A username with letters, numbers, and underscores
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    'username': string;
    /**
     * A password with minimum 8 characters
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    'password': string;
    /**
     * A password with minimum 8 characters
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    'confirmPassword': string;
}
/**
 * 
 * @export
 * @interface CheckUsernameResponse
 */
export interface CheckUsernameResponse {
    /**
     * 
     * @type {string}
     * @memberof CheckUsernameResponse
     */
    'message': string;
    /**
     * 
     * @type {boolean}
     * @memberof CheckUsernameResponse
     */
    'available': boolean;
}
/**
 * 
 * @export
 * @interface CreateItineraryResponse
 */
export interface CreateItineraryResponse {
    /**
     * 
     * @type {CreateItineraryResponseItinerary}
     * @memberof CreateItineraryResponse
     */
    'itinerary': CreateItineraryResponseItinerary;
}
/**
 * 
 * @export
 * @interface CreateItineraryResponseItinerary
 */
export interface CreateItineraryResponseItinerary {
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'startDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'currency': string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateItineraryResponseItinerary
     */
    'isArchived': boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'ownerId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'createdAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItinerary
     */
    'updatedAt': string | null;
    /**
     * 
     * @type {Array<CreateItineraryResponseItineraryItineraryItemsInner>}
     * @memberof CreateItineraryResponseItinerary
     */
    'itineraryItems': Array<CreateItineraryResponseItineraryItineraryItemsInner>;
}
/**
 * 
 * @export
 * @interface CreateItineraryResponseItineraryItineraryItemsInner
 */
export interface CreateItineraryResponseItineraryItineraryItemsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'cost'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'currencyOverride'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'order': number;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'itineraryId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'createdAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'updatedAt': string | null;
    /**
     * 
     * @type {CreateItineraryResponseItineraryItineraryItemsInnerLocation}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInner
     */
    'location'?: CreateItineraryResponseItineraryItineraryItemsInnerLocation | null;
}
/**
 * 
 * @export
 * @interface CreateItineraryResponseItineraryItineraryItemsInnerLocation
 */
export interface CreateItineraryResponseItineraryItineraryItemsInnerLocation {
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'itineraryItemId': string;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'country'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'address'?: string | null;
    /**
     * 
     * @type {CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocation
     */
    'coordinates': CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates;
}
/**
 * 
 * @export
 * @interface CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates
 */
export interface CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates {
    /**
     * 
     * @type {number}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates
     */
    'lat': number;
    /**
     * 
     * @type {number}
     * @memberof CreateItineraryResponseItineraryItineraryItemsInnerLocationCoordinates
     */
    'lng': number;
}
/**
 * A simple error response with a message, and optional array of errors
 * @export
 * @interface ErrorResponseMessage
 */
export interface ErrorResponseMessage {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseMessage
     */
    'message': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponseMessage
     */
    'errors'?: Array<string>;
}
/**
 * 
 * @export
 * @interface FilteredUser
 */
export interface FilteredUser {
    /**
     * User ID
     * @type {string}
     * @memberof FilteredUser
     */
    'id': string;
    /**
     * A username with letters, numbers, and underscores
     * @type {string}
     * @memberof FilteredUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof FilteredUser
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof FilteredUser
     */
    'bio': string | null;
    /**
     * 
     * @type {string}
     * @memberof FilteredUser
     */
    'profilePic': string;
    /**
     * 
     * @type {boolean}
     * @memberof FilteredUser
     */
    'isPrivate': boolean;
    /**
     * A valid email address
     * @type {string}
     * @memberof FilteredUser
     */
    'email': string | null;
}
/**
 * 
 * @export
 * @interface FollowUserResponse
 */
export interface FollowUserResponse {
    /**
     * 
     * @type {string}
     * @memberof FollowUserResponse
     */
    'message': string;
    /**
     * 
     * @type {FollowsIdStatusPatch200ResponseFollow}
     * @memberof FollowUserResponse
     */
    'follow': FollowsIdStatusPatch200ResponseFollow;
}
/**
 * 
 * @export
 * @interface FollowsIdStatusPatch200Response
 */
export interface FollowsIdStatusPatch200Response {
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200Response
     */
    'message': string;
    /**
     * 
     * @type {FollowsIdStatusPatch200ResponseFollow}
     * @memberof FollowsIdStatusPatch200Response
     */
    'follow': FollowsIdStatusPatch200ResponseFollow;
}
/**
 * 
 * @export
 * @interface FollowsIdStatusPatch200ResponseFollow
 */
export interface FollowsIdStatusPatch200ResponseFollow {
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200ResponseFollow
     */
    'status': FollowsIdStatusPatch200ResponseFollowStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200ResponseFollow
     */
    'followedById': string;
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200ResponseFollow
     */
    'followingId': string;
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200ResponseFollow
     */
    'createdAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatch200ResponseFollow
     */
    'updatedAt': string | null;
}

export const FollowsIdStatusPatch200ResponseFollowStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    NotFollowing: 'notFollowing'
} as const;

export type FollowsIdStatusPatch200ResponseFollowStatusEnum = typeof FollowsIdStatusPatch200ResponseFollowStatusEnum[keyof typeof FollowsIdStatusPatch200ResponseFollowStatusEnum];

/**
 * 
 * @export
 * @interface FollowsIdStatusPatchRequest
 */
export interface FollowsIdStatusPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof FollowsIdStatusPatchRequest
     */
    'type': FollowsIdStatusPatchRequestTypeEnum;
}

export const FollowsIdStatusPatchRequestTypeEnum = {
    Accept: 'accept',
    Reject: 'reject',
    Remove: 'remove',
    Cancel: 'cancel',
    Unfollow: 'unfollow'
} as const;

export type FollowsIdStatusPatchRequestTypeEnum = typeof FollowsIdStatusPatchRequestTypeEnum[keyof typeof FollowsIdStatusPatchRequestTypeEnum];

/**
 * 
 * @export
 * @interface GetFollowRequestsResponse
 */
export interface GetFollowRequestsResponse {
    /**
     * 
     * @type {Array<FollowsIdStatusPatch200ResponseFollow>}
     * @memberof GetFollowRequestsResponse
     */
    'pendingRequests': Array<FollowsIdStatusPatch200ResponseFollow>;
}
/**
 * 
 * @export
 * @interface GetFollowStatusResponse
 */
export interface GetFollowStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GetFollowStatusResponse
     */
    'followStatus': GetFollowStatusResponseFollowStatusEnum;
}

export const GetFollowStatusResponseFollowStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    NotFollowing: 'notFollowing'
} as const;

export type GetFollowStatusResponseFollowStatusEnum = typeof GetFollowStatusResponseFollowStatusEnum[keyof typeof GetFollowStatusResponseFollowStatusEnum];

/**
 * 
 * @export
 * @interface GetProfileResponse
 */
export interface GetProfileResponse {
    /**
     * 
     * @type {FilteredUser}
     * @memberof GetProfileResponse
     */
    'user': FilteredUser;
    /**
     * 
     * @type {boolean}
     * @memberof GetProfileResponse
     */
    'isSelf': boolean;
    /**
     * 
     * @type {number}
     * @memberof GetProfileResponse
     */
    'followedByCount': number;
    /**
     * 
     * @type {number}
     * @memberof GetProfileResponse
     */
    'followingCount': number;
    /**
     * 
     * @type {string}
     * @memberof GetProfileResponse
     */
    'followStatus'?: GetProfileResponseFollowStatusEnum;
}

export const GetProfileResponseFollowStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    NotFollowing: 'notFollowing'
} as const;

export type GetProfileResponseFollowStatusEnum = typeof GetProfileResponseFollowStatusEnum[keyof typeof GetProfileResponseFollowStatusEnum];

/**
 * 
 * @export
 * @interface GetUserItinerariesResponse
 */
export interface GetUserItinerariesResponse {
    /**
     * 
     * @type {Array<GetUserItinerariesResponseItinerariesInner>}
     * @memberof GetUserItinerariesResponse
     */
    'itineraries': Array<GetUserItinerariesResponseItinerariesInner>;
    /**
     * 
     * @type {GetUserItinerariesResponsePagination}
     * @memberof GetUserItinerariesResponse
     */
    'pagination': GetUserItinerariesResponsePagination;
}
/**
 * 
 * @export
 * @interface GetUserItinerariesResponseItinerariesInner
 */
export interface GetUserItinerariesResponseItinerariesInner {
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'startDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'endDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'currency': string;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'isArchived': boolean;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'ownerId': string;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'createdAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof GetUserItinerariesResponseItinerariesInner
     */
    'updatedAt': string | null;
}
/**
 * 
 * @export
 * @interface GetUserItinerariesResponsePagination
 */
export interface GetUserItinerariesResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof GetUserItinerariesResponsePagination
     */
    'loadIndex': number;
    /**
     * 
     * @type {boolean}
     * @memberof GetUserItinerariesResponsePagination
     */
    'hasMore': boolean;
}
/**
 * Internal server error response
 * @export
 * @interface InternalServerError
 */
export interface InternalServerError {
    /**
     * 
     * @type {string}
     * @memberof InternalServerError
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof InternalServerError
     */
    'error'?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalServerError
     */
    'errorLocation'?: string;
}
/**
 * 
 * @export
 * @interface ItinerariesIdPatchRequest
 */
export interface ItinerariesIdPatchRequest {
    /**
     * 
     * @type {ItinerariesIdPatchRequestItineraryFields}
     * @memberof ItinerariesIdPatchRequest
     */
    'itineraryFields'?: ItinerariesIdPatchRequestItineraryFields;
    /**
     * 
     * @type {Array<ItinerariesIdPatchRequestUpdatedItemsInner>}
     * @memberof ItinerariesIdPatchRequest
     */
    'updatedItems'?: Array<ItinerariesIdPatchRequestUpdatedItemsInner>;
    /**
     * 
     * @type {Array<ItineraryItemInput>}
     * @memberof ItinerariesIdPatchRequest
     */
    'newItems'?: Array<ItineraryItemInput>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ItinerariesIdPatchRequest
     */
    'deleteItemIds'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ItinerariesIdPatchRequestItineraryFields
 */
export interface ItinerariesIdPatchRequestItineraryFields {
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestItineraryFields
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestItineraryFields
     */
    'description'?: string;
    /**
     * 
     * @type {ModelDate}
     * @memberof ItinerariesIdPatchRequestItineraryFields
     */
    'startDate'?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof ItinerariesIdPatchRequestItineraryFields
     */
    'endDate'?: ModelDate;
}
/**
 * 
 * @export
 * @interface ItinerariesIdPatchRequestUpdatedItemsInner
 */
export interface ItinerariesIdPatchRequestUpdatedItemsInner {
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'cost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'order': number;
    /**
     * 
     * @type {LocationInput}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'location': LocationInput;
    /**
     * 
     * @type {string}
     * @memberof ItinerariesIdPatchRequestUpdatedItemsInner
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface ItinerariesPostRequest
 */
export interface ItinerariesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ItinerariesPostRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ItinerariesPostRequest
     */
    'description'?: string;
    /**
     * 
     * @type {ModelDate}
     * @memberof ItinerariesPostRequest
     */
    'startDate'?: ModelDate;
    /**
     * 
     * @type {ModelDate}
     * @memberof ItinerariesPostRequest
     */
    'endDate'?: ModelDate;
    /**
     * 
     * @type {Array<ItineraryItemInput>}
     * @memberof ItinerariesPostRequest
     */
    'itineraryItems': Array<ItineraryItemInput>;
}
/**
 * 
 * @export
 * @interface ItineraryItemInput
 */
export interface ItineraryItemInput {
    /**
     * 
     * @type {string}
     * @memberof ItineraryItemInput
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ItineraryItemInput
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ItineraryItemInput
     */
    'cost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ItineraryItemInput
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof ItineraryItemInput
     */
    'order': number;
    /**
     * 
     * @type {LocationInput}
     * @memberof ItineraryItemInput
     */
    'location': LocationInput;
}
/**
 * 
 * @export
 * @interface LocationInput
 */
export interface LocationInput {
    /**
     * 
     * @type {LocationInputCoordinates}
     * @memberof LocationInput
     */
    'coordinates': LocationInputCoordinates;
    /**
     * 
     * @type {string}
     * @memberof LocationInput
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationInput
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationInput
     */
    'address'?: string;
}
/**
 * 
 * @export
 * @interface LocationInputCoordinates
 */
export interface LocationInputCoordinates {
    /**
     * 
     * @type {number}
     * @memberof LocationInputCoordinates
     */
    'lat': number;
    /**
     * 
     * @type {number}
     * @memberof LocationInputCoordinates
     */
    'lng': number;
}
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {FilteredUser}
     * @memberof LoginResponse
     */
    'user': FilteredUser;
}
/**
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
}
/**
 * A simple response with a message
 * @export
 * @interface ResponseMessage
 */
export interface ResponseMessage {
    /**
     * 
     * @type {string}
     * @memberof ResponseMessage
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface UpdateItineraryItemRequest
 */
export interface UpdateItineraryItemRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateItineraryItemRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateItineraryItemRequest
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateItineraryItemRequest
     */
    'cost'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateItineraryItemRequest
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateItineraryItemRequest
     */
    'order': number;
    /**
     * 
     * @type {LocationInput}
     * @memberof UpdateItineraryItemRequest
     */
    'location': LocationInput;
    /**
     * 
     * @type {string}
     * @memberof UpdateItineraryItemRequest
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface UsersMeDelete200Response
 */
export interface UsersMeDelete200Response {
    /**
     * 
     * @type {UsersMeDelete200ResponseUser}
     * @memberof UsersMeDelete200Response
     */
    'user': UsersMeDelete200ResponseUser;
}
/**
 * 
 * @export
 * @interface UsersMeDelete200ResponseUser
 */
export interface UsersMeDelete200ResponseUser {
    /**
     * User ID
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'id': string;
    /**
     * A username with letters, numbers, and underscores
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'bio': string | null;
    /**
     * 
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'profilePic': string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersMeDelete200ResponseUser
     */
    'isPrivate': boolean;
    /**
     * A valid email address
     * @type {string}
     * @memberof UsersMeDelete200ResponseUser
     */
    'email': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UsersMeDelete200ResponseUser
     */
    'isDeleted': boolean;
}
/**
 * 
 * @export
 * @interface UsersMeDeleteRequest
 */
export interface UsersMeDeleteRequest {
    /**
     * A password with minimum 8 characters
     * @type {string}
     * @memberof UsersMeDeleteRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UsersMePatch200Response
 */
export interface UsersMePatch200Response {
    /**
     * 
     * @type {FilteredUser}
     * @memberof UsersMePatch200Response
     */
    'user': FilteredUser;
}
/**
 * 
 * @export
 * @interface UsersMePatchRequest
 */
export interface UsersMePatchRequest {
    /**
     * A username with letters, numbers, and underscores
     * @type {string}
     * @memberof UsersMePatchRequest
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMePatchRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersMePatchRequest
     */
    'bio'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Login a user
         * @param {AuthLoginPostRequest} [authLoginPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (authLoginPostRequest?: AuthLoginPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authLoginPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Refresh JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Resend verification email
         * @param {AuthResendVerificationEmailPostRequest} [authResendVerificationEmailPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authResendVerificationEmailPost: async (authResendVerificationEmailPostRequest?: AuthResendVerificationEmailPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/resend-verification-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authResendVerificationEmailPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Signup a user
         * @param {AuthSignupPostRequest} [authSignupPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignupPost: async (authSignupPostRequest?: AuthSignupPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authSignupPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verify email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailPost: async (token: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            assertParamExists('authVerifyEmailPost', 'token', token)
            const localVarPath = `/auth/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (token !== undefined) {
                localVarQueryParameter['token'] = token;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Follow a user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('followsIdGet', 'id', id)
            const localVarPath = `/follows/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Check follow status with this user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdStatusGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('followsIdStatusGet', 'id', id)
            const localVarPath = `/follows/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updated follow status of user
         * @param {string} id User ID
         * @param {FollowsIdStatusPatchRequest} [followsIdStatusPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdStatusPatch: async (id: string, followsIdStatusPatchRequest?: FollowsIdStatusPatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('followsIdStatusPatch', 'id', id)
            const localVarPath = `/follows/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(followsIdStatusPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get following or follower list of a user
         * @param {string} id User ID
         * @param {FollowsIdTypeGetTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdTypeGet: async (id: string, type: FollowsIdTypeGetTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('followsIdTypeGet', 'id', id)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('followsIdTypeGet', 'type', type)
            const localVarPath = `/follows/{id}/{type}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get follow requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsRequestsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/follows/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get an itinerary via id
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('itinerariesIdGet', 'id', id)
            const localVarPath = `/itineraries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an itinerary
         * @param {string} id User ID
         * @param {ItinerariesIdPatchRequest} [itinerariesIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesIdPatch: async (id: string, itinerariesIdPatchRequest?: ItinerariesIdPatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('itinerariesIdPatch', 'id', id)
            const localVarPath = `/itineraries/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(itinerariesIdPatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create an itinerary
         * @param {ItinerariesPostRequest} [itinerariesPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesPost: async (itinerariesPostRequest?: ItinerariesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/itineraries`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(itinerariesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Check if a username is available
         * @param {string} username A username with letters, numbers, and underscores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersCheckUsernameGet: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('usersCheckUsernameGet', 'username', username)
            const localVarPath = `/users/check-username`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get User Profile
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdGet', 'id', id)
            const localVarPath = `/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get the itineraries of a user
         * @param {string} id User ID
         * @param {string} [loadIndex] A positive integer to specify which entries to retrieve for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdItinerariesGet: async (id: string, loadIndex?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersIdItinerariesGet', 'id', id)
            const localVarPath = `/users/{id}/itineraries`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (loadIndex !== undefined) {
                localVarQueryParameter['loadIndex'] = loadIndex;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Soft delete own account
         * @param {UsersMeDeleteRequest} [usersMeDeleteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDelete: async (usersMeDeleteRequest?: UsersMeDeleteRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersMeDeleteRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update own profile
         * @param {UsersMePatchRequest} [usersMePatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePatch: async (usersMePatchRequest?: UsersMePatchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersMePatchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Login a user
         * @param {AuthLoginPostRequest} [authLoginPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(authLoginPostRequest?: AuthLoginPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(authLoginPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Refresh JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRefreshGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRefreshGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authRefreshGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Resend verification email
         * @param {AuthResendVerificationEmailPostRequest} [authResendVerificationEmailPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authResendVerificationEmailPost(authResendVerificationEmailPostRequest?: AuthResendVerificationEmailPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authResendVerificationEmailPost(authResendVerificationEmailPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authResendVerificationEmailPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Signup a user
         * @param {AuthSignupPostRequest} [authSignupPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authSignupPost(authSignupPostRequest?: AuthSignupPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authSignupPost(authSignupPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Verify email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyEmailPost(token: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyEmailPost(token, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.authVerifyEmailPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Follow a user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FollowUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.followsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Check follow status with this user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followsIdStatusGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFollowStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followsIdStatusGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.followsIdStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updated follow status of user
         * @param {string} id User ID
         * @param {FollowsIdStatusPatchRequest} [followsIdStatusPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followsIdStatusPatch(id: string, followsIdStatusPatchRequest?: FollowsIdStatusPatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FollowsIdStatusPatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followsIdStatusPatch(id, followsIdStatusPatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.followsIdStatusPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get following or follower list of a user
         * @param {string} id User ID
         * @param {FollowsIdTypeGetTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followsIdTypeGet(id: string, type: FollowsIdTypeGetTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFollowStatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followsIdTypeGet(id, type, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.followsIdTypeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get follow requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async followsRequestsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFollowRequestsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.followsRequestsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.followsRequestsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get an itinerary via id
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async itinerariesIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateItineraryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.itinerariesIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.itinerariesIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an itinerary
         * @param {string} id User ID
         * @param {ItinerariesIdPatchRequest} [itinerariesIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async itinerariesIdPatch(id: string, itinerariesIdPatchRequest?: ItinerariesIdPatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateItineraryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.itinerariesIdPatch(id, itinerariesIdPatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.itinerariesIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Create an itinerary
         * @param {ItinerariesPostRequest} [itinerariesPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async itinerariesPost(itinerariesPostRequest?: ItinerariesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateItineraryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.itinerariesPost(itinerariesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.itinerariesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Check if a username is available
         * @param {string} username A username with letters, numbers, and underscores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersCheckUsernameGet(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckUsernameResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersCheckUsernameGet(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersCheckUsernameGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get User Profile
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the itineraries of a user
         * @param {string} id User ID
         * @param {string} [loadIndex] A positive integer to specify which entries to retrieve for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersIdItinerariesGet(id: string, loadIndex?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserItinerariesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersIdItinerariesGet(id, loadIndex, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersIdItinerariesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Soft delete own account
         * @param {UsersMeDeleteRequest} [usersMeDeleteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeDelete(usersMeDeleteRequest?: UsersMeDeleteRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersMeDelete200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeDelete(usersMeDeleteRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersMeDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update own profile
         * @param {UsersMePatchRequest} [usersMePatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMePatch(usersMePatchRequest?: UsersMePatchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersMePatch200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMePatch(usersMePatchRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.usersMePatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Login a user
         * @param {AuthLoginPostRequest} [authLoginPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(authLoginPostRequest?: AuthLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.authLoginPost(authLoginPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<ResponseMessage> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Get me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authMeGet(options?: RawAxiosRequestConfig): AxiosPromise<LoginResponse> {
            return localVarFp.authMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Refresh JWT
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshGet(options?: RawAxiosRequestConfig): AxiosPromise<ResponseMessage> {
            return localVarFp.authRefreshGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Resend verification email
         * @param {AuthResendVerificationEmailPostRequest} [authResendVerificationEmailPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authResendVerificationEmailPost(authResendVerificationEmailPostRequest?: AuthResendVerificationEmailPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseMessage> {
            return localVarFp.authResendVerificationEmailPost(authResendVerificationEmailPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Signup a user
         * @param {AuthSignupPostRequest} [authSignupPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authSignupPost(authSignupPostRequest?: AuthSignupPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseMessage> {
            return localVarFp.authSignupPost(authSignupPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verify email
         * @param {string} token 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyEmailPost(token: string, options?: RawAxiosRequestConfig): AxiosPromise<ResponseMessage> {
            return localVarFp.authVerifyEmailPost(token, options).then((request) => request(axios, basePath));
        },
        /**
         * Follow a user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<FollowUserResponse> {
            return localVarFp.followsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Check follow status with this user
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdStatusGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetFollowStatusResponse> {
            return localVarFp.followsIdStatusGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Updated follow status of user
         * @param {string} id User ID
         * @param {FollowsIdStatusPatchRequest} [followsIdStatusPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdStatusPatch(id: string, followsIdStatusPatchRequest?: FollowsIdStatusPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<FollowsIdStatusPatch200Response> {
            return localVarFp.followsIdStatusPatch(id, followsIdStatusPatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Get following or follower list of a user
         * @param {string} id User ID
         * @param {FollowsIdTypeGetTypeEnum} type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsIdTypeGet(id: string, type: FollowsIdTypeGetTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<GetFollowStatusResponse> {
            return localVarFp.followsIdTypeGet(id, type, options).then((request) => request(axios, basePath));
        },
        /**
         * Get follow requests
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        followsRequestsGet(options?: RawAxiosRequestConfig): AxiosPromise<GetFollowRequestsResponse> {
            return localVarFp.followsRequestsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get an itinerary via id
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateItineraryResponse> {
            return localVarFp.itinerariesIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an itinerary
         * @param {string} id User ID
         * @param {ItinerariesIdPatchRequest} [itinerariesIdPatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesIdPatch(id: string, itinerariesIdPatchRequest?: ItinerariesIdPatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateItineraryResponse> {
            return localVarFp.itinerariesIdPatch(id, itinerariesIdPatchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Create an itinerary
         * @param {ItinerariesPostRequest} [itinerariesPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        itinerariesPost(itinerariesPostRequest?: ItinerariesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateItineraryResponse> {
            return localVarFp.itinerariesPost(itinerariesPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Check if a username is available
         * @param {string} username A username with letters, numbers, and underscores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersCheckUsernameGet(username: string, options?: RawAxiosRequestConfig): AxiosPromise<CheckUsernameResponse> {
            return localVarFp.usersCheckUsernameGet(username, options).then((request) => request(axios, basePath));
        },
        /**
         * Get User Profile
         * @param {string} id User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetProfileResponse> {
            return localVarFp.usersIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get the itineraries of a user
         * @param {string} id User ID
         * @param {string} [loadIndex] A positive integer to specify which entries to retrieve for pagination
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersIdItinerariesGet(id: string, loadIndex?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserItinerariesResponse> {
            return localVarFp.usersIdItinerariesGet(id, loadIndex, options).then((request) => request(axios, basePath));
        },
        /**
         * Soft delete own account
         * @param {UsersMeDeleteRequest} [usersMeDeleteRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeDelete(usersMeDeleteRequest?: UsersMeDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersMeDelete200Response> {
            return localVarFp.usersMeDelete(usersMeDeleteRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Update own profile
         * @param {UsersMePatchRequest} [usersMePatchRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePatch(usersMePatchRequest?: UsersMePatchRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersMePatch200Response> {
            return localVarFp.usersMePatch(usersMePatchRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Login a user
     * @param {AuthLoginPostRequest} [authLoginPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authLoginPost(authLoginPostRequest?: AuthLoginPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authLoginPost(authLoginPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Logout a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authMeGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Refresh JWT
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authRefreshGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authRefreshGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Resend verification email
     * @param {AuthResendVerificationEmailPostRequest} [authResendVerificationEmailPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authResendVerificationEmailPost(authResendVerificationEmailPostRequest?: AuthResendVerificationEmailPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authResendVerificationEmailPost(authResendVerificationEmailPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Signup a user
     * @param {AuthSignupPostRequest} [authSignupPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authSignupPost(authSignupPostRequest?: AuthSignupPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authSignupPost(authSignupPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verify email
     * @param {string} token 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public authVerifyEmailPost(token: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).authVerifyEmailPost(token, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Follow a user
     * @param {string} id User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public followsIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).followsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Check follow status with this user
     * @param {string} id User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public followsIdStatusGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).followsIdStatusGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updated follow status of user
     * @param {string} id User ID
     * @param {FollowsIdStatusPatchRequest} [followsIdStatusPatchRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public followsIdStatusPatch(id: string, followsIdStatusPatchRequest?: FollowsIdStatusPatchRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).followsIdStatusPatch(id, followsIdStatusPatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get following or follower list of a user
     * @param {string} id User ID
     * @param {FollowsIdTypeGetTypeEnum} type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public followsIdTypeGet(id: string, type: FollowsIdTypeGetTypeEnum, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).followsIdTypeGet(id, type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get follow requests
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public followsRequestsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).followsRequestsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get an itinerary via id
     * @param {string} id User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public itinerariesIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).itinerariesIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an itinerary
     * @param {string} id User ID
     * @param {ItinerariesIdPatchRequest} [itinerariesIdPatchRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public itinerariesIdPatch(id: string, itinerariesIdPatchRequest?: ItinerariesIdPatchRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).itinerariesIdPatch(id, itinerariesIdPatchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create an itinerary
     * @param {ItinerariesPostRequest} [itinerariesPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public itinerariesPost(itinerariesPostRequest?: ItinerariesPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).itinerariesPost(itinerariesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Check if a username is available
     * @param {string} username A username with letters, numbers, and underscores
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersCheckUsernameGet(username: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersCheckUsernameGet(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get User Profile
     * @param {string} id User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersIdGet(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the itineraries of a user
     * @param {string} id User ID
     * @param {string} [loadIndex] A positive integer to specify which entries to retrieve for pagination
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersIdItinerariesGet(id: string, loadIndex?: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersIdItinerariesGet(id, loadIndex, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Soft delete own account
     * @param {UsersMeDeleteRequest} [usersMeDeleteRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersMeDelete(usersMeDeleteRequest?: UsersMeDeleteRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersMeDelete(usersMeDeleteRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update own profile
     * @param {UsersMePatchRequest} [usersMePatchRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public usersMePatch(usersMePatchRequest?: UsersMePatchRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).usersMePatch(usersMePatchRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const FollowsIdTypeGetTypeEnum = {
    FollowedBy: 'followedBy',
    Following: 'following'
} as const;
export type FollowsIdTypeGetTypeEnum = typeof FollowsIdTypeGetTypeEnum[keyof typeof FollowsIdTypeGetTypeEnum];


